name: Deploy Google Spreadsheet Scaper API

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" > .env
          echo "GOOGLE_CLIENT_REDIRECT_URI=${{ secrets.GOOGLE_CLIENT_REDIRECT_URI }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env
          echo "SPREADSHEET_RANGE=${{ secrets.SPREADSHEET_RANGE }}" >> .env
          echo "WEB_APP_PORT=${{ secrets.WEB_APP_PORT }}" >> .env
          echo "FILE_TO_SAVE_TOKENS=${{ secrets.FILE_TO_SAVE_TOKENS }}" >> .env
          echo "DATA_MEZI_MAX_PERSON=${{ secrets.DATA_MEZI_MAX_PERSON }}" >> .env
          echo "DATA_DOBORGAZ_MAX_PERSON=${{ secrets.DATA_DOBORGAZ_MAX_PERSON }}" >> .env

      - name: Remove unnecessary files
        run: |
          rm -rf .git
          rm -rf .github

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: './'
          remote_path: '/'
          sftp_only: true
          password: ${{ secrets.SFTP_PW }}